name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js (if your project uses Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          zip -r deploy.zip .
          aws elasticbeanstalk create-application-version --application-name <YourAppName> --version-label v1 --source-bundle S3Bucket=<YourS3Bucket>,S3Key=deploy.zip
          aws elasticbeanstalk update-environment --application-name <YourAppName> --environment-name <YourEnvName> --version-label v1

